name: bishub_app
description: BisHub project

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

fonts:
  - family: MyFont
    fonts:
      - asset: fonts/Roboto-Medium.ttf
        weight: 500


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_screenutil:
  dots_indicator:
  intl:
  cloud_firestore:
  firebase_auth: ^4.7.2
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/walking-png.png
    - assets/images/bg-shape.png
    - assets/icons/lock.png
    - assets/images/sierra.png
    - assets/images/ololo.png
    - assets/images/engl_school.png
    - assets/images/zerno.png
    - assets/images/noname.png
    - assets/images/gapar.png
    - assets/images/ants.png
    - assets/images/bellagio.png
    - assets/images/adriano.png
    - assets/images/startup.png
    - assets/images/medicine.png
    - assets/images/ilgeri.png
    - assets/images/devkit.png
    - assets/images/kspace.png
    - assets/images/uiux.png



